<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>Nodalis.SmokeTests</RootNamespace>
    <AssemblyName>Nodalis.SmokeTests</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Nodalis.Core\Nodalis.Core.csproj" />
    <ProjectReference Include="..\..\src\Nodalis.Infrastructure\Nodalis.Infrastructure.csproj" />
  </ItemGroup>
</Project>
